### PR TITLE
Add Fpdf bill footer

### PR DESCRIPTION
**Pull request by Franco2911**

### CODE REVIEW

**Comment by sprain** [comment]
Thank you! I will have a look at this.

**Comment by sprain** [comment]
I did not look at the output of this code yet, but we should  make it compatible with `Sprain\SwissQrBill\PaymentPart\Output\OutputInterface` and `Sprain\SwissQrBill\PaymentPart\Output\AbstractOutput`.

**Comment by Franco2911** [comment]
> I did not look at the output of this code yet, but we should make it compatible with `Sprain\SwissQrBill\PaymentPart\Output\OutputInterface` and `Sprain\SwissQrBill\PaymentPart\Output\AbstractOutput`.

Ok, I will try to do that the next week, I've no time yet.

**Comment by Franco2911** [comment]
I worked on the FPDF addon, now I have a problem with placeholders because Fpdf does not accept svg.
Is it possible to add png placeholders images?
And what do you prefere for this a separate library like TcPdf or a PR in your Librairy?

**Comment by sprain** [comment]
> I worked on the FPDF addon

Thank you!

> Fpdf does not accept svg. Is it possible to add png placeholders images?

That's possible. The files are even officially available as downloads:
https://www.paymentstandards.ch/de/shared/communication-grid/eckmarken.html

> what do you prefere for this a separate library like TcPdf or a PR in your Librairy?

TcPDF is now integrated in this library. See `PaymentPart/Output/TcPdfOutput`. For me, this is the preferred way.

**Comment by Franco2911** [comment]
ok I will close my issue with images and prepare a new PR.

**Comment by sprain** [comment]
Replaced by #59

**Pull request closed without merging**
