### PR TITLE
Add empty line before alternative schemes, if needed

### LINKED ISSUE #142: Definition of StrdBkgInf changed in specifications v2.2
AlternativeScheme (field 33) is always sent, even though it is a empty array.

This triggers a note/warning in the postfinance validator: "The element 'AltPmt' may only be delivered if it is also filled."

### PR DESCRIPTION
**Pull request by sprain**
Fixes #142
See https://github.com/sprain/php-swiss-qr-bill/issues/142#issuecomment-1795314141

Fixes a situation where an additional empty line needs to be added if there is no `billInformation` but there are `alternativeSchemes`.

### CODE REVIEW

**Comment by demianh** [comment]
I can confirm this solves my problem from https://github.com/sprain/php-swiss-qr-bill/issues/142#issuecomment-1795314141

**Comment by demianh** [comment]
The validator shows a warning (not an error!) for the generated QR code:

> (0048) - Element <StrdBkgInf> must only be deliverd if the element ist not empty. Exception: If subsequent elements are provided.

But i guess, that is a problem of the validator, that it can't handle the Exception.

Full validator output: [Protocol.txt](https://github.com/sprain/php-swiss-qr-bill/files/13362299/Protocol.txt)

**Comment by sprain** [comment]
Thanks for testing!

I am pretty sure that the validator is currently broken. I am in touch with SIX. See #241.

I will give them a few more days to get back to me again. Maybe we can then merge this with successfully validated qr codes.

**Comment by sprain** [comment]
Ok, SIX replied. This state of things is the best they can do in the validator ;) The warning will always be shown, even if the exception applies.

**Pull request merged**
