### PR TITLE
Fix handling UTF-8 characters in FpdfOutput and TcPdfOutput

### LINKED ISSUE #131: Hello, i am using tcpdf as output option. Here is my code
Hello, i am using tcpdf as output option. Here is my code

`$tcPdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8');`
`$tcPdf->setPrintHeader(false);`
`$tcPdf->setPrintFooter(false);`
`$tcPdf->AddPage();`
`$output = new QrBill\PaymentPart\Output\TcPdfOutput\TcPdfOutput($qrBill, 'en', $tcPdf);`
`$output->setPrintable(false)->getPaymentPart();`

_Originally posted by @onebeat in https://github.com/sprain/php-swiss-qr-bill/issues/130#issuecomment-856123200_

### PR DESCRIPTION
**Pull request by KamilPesek**
Fixes #131

### CODE REVIEW

**Comment by sprain** [comment]
Thank you!

The [style guide](https://github.com/sprain/php-swiss-qr-bill/blob/master/docs/specs/style-guide-en.pdf) states:

> The following sans-serif fonts are permitted:
> – Arial
> – Frutiger
> – Helvetica
> – Liberation Sans

Therefore I don't think we should allow the font to be as flexible as this pr makes it.
Maybe we could instead provide a utf8-compatible font which is fixed within this library. What do you think?

**Comment by KamilPesek** [comment]
I have to say I am lost. I tried to played with FpdfOutput but with no success. I tried some test code like
image
( I tried to add custom Helvetica and Frutiger generated from ttf from here http://www.fpdf.org/makefont/make.php)

Font has been added, font is also set (I can see it's used) but it has still problem with _ěčřšžýýáíé_
image

**Comment by KamilPesek** [comment]
Ok, so I was on false lead. Problem was in this library. I added convertText() which I believe could fix it.

**Comment by KamilPesek** [comment]
@sprain how should I proceed?

**Comment by KamilPesek** [comment]
Hm, thinking what could be the difference:
image

I am on Windows 10, CRLF

```
$fpdf = new \Fpdf\Fpdf('P', 'mm', 'A4');
$fpdf->AddPage();

$output = new FpdfOutput($qrBill, 'de', $fpdf);
$output
    ->setPrintable(false)
    ->getPaymentPart();

@$qrPdfTempPath = tempnam('tmp', 'test.pdf');
$fpdf->Output($qrPdfTempPath, 'F');

header('Content-type: application/pdf');
header('Content-Disposition: inline; filename="' . $qrPdfTempPath . '"');
header('Content-Transfer-Encoding: binary');
header('Accept-Ranges: bytes');
echo file_get_contents($qrPdfTempPath);

```

**Comment by KamilPesek** [comment]
> I use utf8_decode()  

That's what I had to replace to make it work. At least at my computer. The question is why it works differently for me. I also tried it on our Linux server and it worked there.

**Comment by sprain** [comment]
Looks like we're kinda stuck here 🤔
Good ideas are welcome.

**Comment by Franco2911** [comment]
I made many and many tests before a good result. 

Your entire flow must be UTF8 compliant. 

You have to use utf8 decode on each rows(cell and multicell)

**Comment by sprain** [comment]
Closing this due to missing activity. Feel free to re-open if there is a need.

**Pull request closed without merging**
