### PR TITLE
Support PhpWordOutput format

### PR DESCRIPTION
**Pull request by sevjan**
In our enviroment we often use the [PhpOffice/PhpWord](https://github.com/PHPOffice/PHPWord) library. With a Office Word ouput the user has more flexiblity to change the document afterwards. With the existing Html/Pdf outputs we could not achive that. (An option would have been with ImageMagick to render a TCPDF, convert it to PNG, cut out the payment part and add it to the word document. But the drawback would haven been to require all the ImageMagick stuff and to install the extesion.)

Therefore I added a PhpWordOutput version. I have tried to follow best practices as much as possible and to meet the code style. If I missunderstood something please let me know to correct it.
For exacte position I hade to use some ugly nested tables. But if nothing is to be changed in the QR invoice part anyway, it shouldn't matter.

Of course, this output is a slightly different one because it can be edited afterwards due to the Office Word format. So I could understand if you don't want to have this kind of export in the core library.

If you need any further information or test for this PR just let me know.
And don't forget for my first PR
> Be nice to each other.

### CODE REVIEW

**Comment by sprain** [comment]
Hey @sevjan – thank you for the pull request. Interesting application that I would not have thought of :) I will gladly have a look at this pr as soon as I find the time to do so.

**Comment by sprain** [comment]
I had a first look. This seems a nice implementation. There are two things we need to have a closer look:

* Tests are failing
* I get this deprecation notice, which maybe we can get rid of: https://github.com/PHPOffice/PHPWord/issues/2204

If you [allow me to edit this branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), I can help working on it without needing to open a new pr.

**Comment by sevjan** [comment]
Thank you for your prompt reply.
That sounds good. Of course you can edit this branch. (If I see it right [you already can](https://user-images.githubusercontent.com/48485375/169907456-b3edb4f9-e932-4734-84fa-e96241e42193.png).)

1. Locally the test run fine (on Windows 10 / PHP 8.0). I choose tow compare in a same manner than tcpdf/fpdf but for the PhpWord I needed in addition to extract the `.docx` files with `\ZipArchive`. The `chunk_split` was just for better comaprison on to long one liner.
2. Unfortunately, I can not test on +8.1.0 at the moment. If you can fix that, that would be great.

**Comment by sprain** [comment]
Closing due to inactivity and obviously missing demand.

**Pull request closed without merging**
