### PR TITLE
Add QR-Code options method

### PR DESCRIPTION
**Pull request by sdespont**
Details https://github.com/sprain/php-swiss-qr-bill/issues/249

### CODE REVIEW

**Comment by sdespont** [comment]
@sprain, what's the point of automatically executing tests in the workflow if they can't succeed? This test only works in a hardened environment”.

**Comment by kohlerdominik** [comment]
I think the test fails because "prefer-lowest" will go for the lowest allowed endroid-version, which is `4.4.4`, and this version does not have `Endroid\QrCode\Writer\SvgWriter::WRITER_OPTION_COMPACT` I guess?

The fix would be to remove `endroid/qr-code: ^4.4.4` from composer.json. Is there reason to keep the compatibility?

**Comment by sdespont** [comment]
I think we should drop EOL PHP 8.0 permitting to drop `endroid/qr-code: ^4`

@sprain ok for you ?

**Comment by sprain** [comment]
Thanks for the PR!

> I think we should drop EOL PHP 8.0 permitting to drop endroid/qr-code: ^4

I remember the backlash when I dropped support for `endroid/qr-code: ^3` too soon 😅
Also, PHP 8.0 still counts for [20% of all installs](https://github.com/sprain/php-swiss-qr-bill/assets/260361/015753dd-fad2-4676-8188-dd51950f5c6c) of this library, and [even 25% for v4](https://github.com/sprain/php-swiss-qr-bill/assets/260361/7f5f07de-2a1e-4ad6-954a-eb57dce430ef) of this library. 

Therefore, the way to go would be to add parallel support for both versions, before dropping the older one. We already do that in the constructor of `QrCode`.

**Comment by sdespont** [comment]
ok, it means that `Endroid\QrCode\Writer\SvgWriter::WRITER_OPTION_COMPACT` cannot be used and we need to harcode the option key "compact" instead. I have pushed a commit for that

**Comment by kohlerdominik** [comment]
@sprain Tests in `prefer-stable` & `>8.1` are not only failing, but also taking >15Minutes compared to the <15Seconds that they used to take.

**Comment by sprain** [comment]
Replaced by #252

**Pull request closed without merging**
