### PR TITLE
PSR-4 compatibility

### LINKED ISSUE #83: PSR-4 compatibility
I'm receiving this error:

```Deprecation Notice: Class Sprain\Tests\SwissQrBill\PaymentPart\Output\HtmlOutput\TcPdfOutputTest located in ./vendor/sprain/swiss-qr-bill/tests/PaymentPart/Output/TcPdfOutput/TcPdfOutputTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201```

It seems it's just matter of making the class name ( and namespace ) match with the file path and name.

### PR DESCRIPTION
**Pull request by Shkryob**
Fixes #83

### CODE REVIEW

**Comment by kohlerdominik** [comment]
It looks like somehow a the pipeline couldn't run because it couln't prepare the container. @sprain can you rerun the pipeline?

**Comment by sprain** [comment]
Thank you guys 🙌

**Comment by kohlerdominik** [comment]
@sprain any idea why the release is not pushed to packagist?
grafik

**Comment by sprain** [comment]
@kohlerdominik Hmmm ... it should auto-update. Will have a look.

**Comment by sprain** [comment]
@kohlerdominik I am clueless. I have to escalate this into something larger … #85

**Pull request merged**
