### PR TITLE
Add mpdf output

### PR DESCRIPTION
**Pull request by Hativ**
Copied fpdf output and changed it to support mpdf.

The only functional change to the fpdf output is that the font can be changed in the constructor.

### CODE REVIEW

**Comment by sprain** [comment]
Thanks for your contribution!

I am no expert when it comes to mPDF. What's the benefit of this approach compared to using HtmlOutput [and then rendering it with mPDF](https://mpdf.github.io/getting-started/html-or-php.html)? After all, turning html into a pdf seems to be [the main purpose of mPDF](https://mpdf.github.io).

**Comment by Hativ** [comment]
I tried HtmlOutput first, but mPDF doesn't rendered it very well. Therefore I created MpdfOutput.

**Comment by sprain** [comment]
I see that an `MpdfOutput` could be a good extension to this library. But this seems like a lot of copied code. Maybe a better approach can be found? Feel free to add your ideas here.

**Comment by sprain** [comment]
Closing now due to inactivity. Feel free to re-open if needed.

**Comment by DavidBrogli** [comment]
Very big thank you for the code. It has brought me further. Too bad it was never added to the repository. 
@Hativ @sprain

**Comment by DavidBrogli** [comment]
For example:
` $this->pdf->AddPage();
$this->pdf->SetHTMLFooter("");
$this->pdf->WriteHTML('<h2>QR Code Einzahlungsschein</h2>');
$output = new Sprain\SwissQrBill\PaymentPart\Output\MpdfOutput\MpdfOutput($qrBill, 'de', $this->pdf);
$html = $output->setPrintable(false)->getPaymentPart();`

**Pull request closed without merging**
