### PR TITLE
Replace TravisCi with Github Actions

### PR DESCRIPTION
**Pull request by kohlerdominik**
Fix for broken travis setup.

Some very old versions of symfony/validator seem not to work properly with composers `--prefer-lowest` flag. I had to remove them. But they both are pretty outdated:
- 3.4 reached end of life 6 months ago (has bugfixes until november 2021)
- 4.2 reached end of life 2 years ago

Also, i had to update friendsofphp/php-cs-fixer and phpstan/phpstan which both did fail in `-prefer-lowest`. However, as they are dev-dependencies only, this should not really matter.

Checks should be all the same as they were in travis, but please check it yourself. Also check the [test run](https://github.com/lextira/php-swiss-qr-bill/actions/runs/832212619).

### CODE REVIEW

**Comment by sprain** [comment]
`composer update --prefer-lowest --prefer-dist --no-interaction` works fine for me on this branch with PHP 7.4

**Comment by kohlerdominik** [comment]
Update: good news!

I got an error message (by accident), and was able to find the solution. It was fixed in later package-version.

I restricted the version for 3.4.x to the latest release, and now it works.

**Comment by kohlerdominik** [comment]
It will only be available once it's on the primary branch of the repo.

**Comment by sprain** [comment]
Works great! https://github.com/sprain/php-swiss-qr-bill/actions

**Pull request merged**
