### PR TITLE
Update tests to use PHPUnit 9

### PR DESCRIPTION
**Pull request by Franco2911**
There are two skipped tests left, but it looks like that's what you want. If not juste change this by removing "!":

```
if (!is_writable(dirname($testfile))) {
            $this->markTestSkipped();
            return;
        }
```

### CODE REVIEW

**Comment by Franco2911** [comment]
At this point I don't know how to resolve Travis check in PREFER_LOWEST="--prefer-lowest" mode.
it seems the problem is in the Symfony Validator return typing of SetUp. Must be : 

`public function setUp(): void` 

`PHP Fatal error:  Declaration of Symfony\Component\Validator\Test\ConstraintValidatorTestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/travis/build/sprain/php-swiss-qr-bill/vendor/symfony/validator/Test/ConstraintValidatorTestCase.php on line 30`

thank you for feedback about that.

**Comment by sprain** [comment]
Thanks a lot for your work here, @Franco2911!

> At this point I don't know how to resolve Travis check in PREFER_LOWEST="--prefer-lowest" mode.

There's two things we can do:
* Bump minimal version of `symfony/validator` to 3.4.31. I think that should be no problem.
* Drop support for PHP 7.2. I think that should be justifiable, too.

**Comment by Franco2911** [comment]
> * Bump minimal version of `symfony/validator` to 3.4.31. I think that should be no problem.
> * Drop support for PHP 7.2. I think that should be justifiable, too.

Thank you, I agree with this, but I think we have to informe on the new version that php 7.2 is no longer supported.
For symfony/validator` to 3.4.31 Like you I think that should be no problem.

I think it is better if you make the modification, after last PR there are some conflict and I am not abble to correct this.
Let me know.

**Comment by sprain** [comment]
Replaced by #80

**Pull request closed without merging**
