### PR TITLE
Add support for endroid/qrcode v4

### LINKED ISSUE #133: Compatibility with endroid/qrcode 4.x
Hi, 

I wanted to install:

https://github.com/sprain/php-swiss-qr-bill
https://github.com/smhg/sepa-qr-data-php
https://github.com/endroid/qr-code

Using php 7.4 on a mac with mamp

But I get this error:

composer require endroid/qr-code -W                    
Using version ^4.1 for endroid/qr-code
./composer.json has been updated
Running composer update endroid/qr-code --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sprain/swiss-qr-bill is locked to version v3.1 and an update of this package was not requested.
    - sprain/swiss-qr-bill v3.1 requires endroid/qr-code ^3.9.7 -> found endroid/qr-code[3.9.7] but it conflicts with your root composer.json require (^4.1).

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### PR DESCRIPTION
**Pull request by sprain**
Closed #133 

Adds support for `endroid/qrcode` dependency in version 4.x.
This contains bc breaks as `Sprain\SwissQrBill\QrCode\QrCode` no longer extends `Endroid\QrCode\QrCode`.

* https://github.com/endroid/qr-code/releases/tag/4.0.0
* https://github.com/endroid/qr-code/tags

**Todos**

- [x] TcPdfOutputs are missing swiss cross in qr code. https://github.com/endroid/qr-code/pull/359
- [x] Wait for new release of `endroid/qrcode`  to contain the above bugfix
- [x] Bug in v4 which creates blurry shapes? https://github.com/endroid/qr-code/issues/355

~- [ ] Re-add backwards compatibility with version `^3.9.7`~

### CODE REVIEW

**Comment by dominikschnieper** [comment]
Hi @sprain, can i help to finish this pr? I need it for a project which depends on endroid/qrcode v4.

**Comment by sprain** [comment]
Looks like the blocker was just fixed, so I‘ll have a look again soon.

https://github.com/endroid/qr-code/issues/355#issuecomment-991906495

**Comment by sprain** [comment]
@dominikschnieper  If you want, you can help find the reason for the missing swiss cross in TcPdfOutput.

**Comment by dominikschnieper** [comment]
There is a problem inside endroid SvgWriter on Line 104 which misses the namespace argument. Should be like this:
`$imageDefinition->addAttribute('xlink:href', $logoImageData->createDataUri(), "http://www.w3.org/1999/xlink");`

Second thing is in QrCode.php on line 103 has to be like this:
`[SvgWriter::WRITER_OPTION_FORCE_XLINK_HREF => true]`

**Comment by sprain** [comment]
@dominikschnieper 
I create a pr to fix the bug in `SvgWriter`:
https://github.com/endroid/qr-code/pull/359

**Comment by sprain** [comment]
@dominikschnieper 
While not completely done yet, this branch should now be functional. You can use it as `"sprain/swiss-qr-bill": "dev-endroid-qrcode-v4"` in your code to continue development.

**Comment by sprain** [comment]
@dominikschnieper 
https://github.com/sprain/php-swiss-qr-bill/releases/tag/v4.0 is now released.

**Pull request merged**
